services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=Matei'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser2'
    ports:
      - '3306:3306'
